<table>
    <thead>
        <tr>
            <th colspan="11" style="font-weight: bold; font-size: 14px;">LAPORAN ANALISIS OEE (OVERALL EQUIPMENT EFFECTIVENESS)</th>
        </tr>
        <tr>
            <td colspan="11"><strong>Departemen:</strong> {{ $departmentCode }}</td>
        </tr>
        <tr>
            <td colspan="11"><strong>Scope Mesin:</strong> {{ $selectedMachine ?: 'Semua Mesin' }}</td>
        </tr>
        <tr>
            <td colspan="11"><strong>Periode:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} s/d {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}</td>
        </tr>
        <tr>
            <td colspan="11"><strong>Generated By:</strong> {{ $generated_by }}</td>
        </tr>
        <tr>
            <td colspan="11"><strong>Generated At:</strong> {{ $generated_at }}</td>
        </tr>
        <tr>
            <td colspan="11"><strong>IP Address:</strong> {{ $generated_ip }}</td>
        </tr>
        <tr>
            <td colspan="11"></td>
        </tr>
        <tr style="background-color: #f3f4f6; font-weight: bold;">
            <th>Tanggal</th>
            <th>Planned Capacity (Jam)</th>
            <th>Work Hours (Jam)</th>
            <th>Downtime (Jam)</th>
            <th>Target Qty</th>
            <th>Actual Qty</th>
            <th>Reject Qty</th>
            <th>Availability (%)</th>
            <th>Performance (%)</th>
            <th>Quality (%)</th>
            <th>OEE (%)</th>
        </tr>
    </thead>
    <tbody>
        @foreach($rows as $row)
            @php
                $isHoliday = $row['planned_capacity'] == 0;
                $rowStyle = $isHoliday ? 'background-color: #f3f4f6; color: #9ca3af;' : '';
            @endphp
            <tr style="{{ $rowStyle }}">
                <td>{{ \Carbon\Carbon::parse($row['date'])->format('d/m/Y') }}</td>
                <td>{{ $row['planned_capacity'] }}</td>
                <td>{{ $row['work_hours'] }}</td>
                <td>{{ $row['downtime_hours'] }}</td>
                <td>{{ $row['target_qty'] }}</td>
                <td>{{ $row['actual_qty'] }}</td>
                <td>{{ $row['reject_qty'] }}</td>
                <td>{{ $row['availability'] !== null ? $row['availability'] : '-' }}</td>
                <td>{{ $row['performance'] !== null ? $row['performance'] : '-' }}</td>
                <td>{{ $row['quality'] !== null ? $row['quality'] : '-' }}</td>
                <td>{{ $row['oee'] !== null ? $row['oee'] : '-' }}</td>
            </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr style="font-weight: bold; background-color: #e5e7eb;">
            <td>TOTAL / RINGKASAN PERIODE</td>
            <td>{{ $summary['planned_capacity'] }}</td>
            <td>{{ $summary['work_hours'] }}</td>
            <td>{{ $summary['downtime_hours'] }}</td>
            <td>{{ $summary['target_qty'] }}</td>
            <td>{{ $summary['actual_qty'] }}</td>
            <td>{{ $summary['reject_qty'] }}</td>
            <td>{{ $summary['availability'] !== null ? $summary['availability'] : '-' }}</td>
            <td>{{ $summary['performance'] !== null ? $summary['performance'] : '-' }}</td>
            <td>{{ $summary['quality'] !== null ? $summary['quality'] : '-' }}</td>
            <td>{{ $summary['oee'] !== null ? $summary['oee'] : '-' }}</td>
        </tr>
    </tfoot>
</table>
