<table>
    <thead>
        <tr>
            <th colspan="10" style="font-weight: bold; font-size: 14px;">LAPORAN ANALISIS OEE (OVERALL EQUIPMENT EFFECTIVENESS)</th>
        </tr>
        <tr>
            <td colspan="10"><strong>Departemen:</strong> {{ $departmentCode }}</td>
        </tr>
        <tr>
            <td colspan="10"><strong>Scope Mesin:</strong> {{ $selectedMachine ?: 'Semua Mesin' }}</td>
        </tr>
        <tr>
            <td colspan="10"><strong>Periode:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} s/d {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}</td>
        </tr>
        <tr>
            <td colspan="10"><strong>Generated By:</strong> {{ $generated_by }}</td>
        </tr>
        <tr>
            <td colspan="10"><strong>Generated At:</strong> {{ $generated_at }}</td>
        </tr>
        <tr>
            <td colspan="10"><strong>IP Address:</strong> {{ $generated_ip }}</td>
        </tr>
        <tr>
            <td colspan="10"></td>
        </tr>
        <tr style="background-color: #f3f4f6; font-weight: bold;">
            <th>Tanggal</th>
            <th>Total Runtime Mesin (Jam)</th>
            <th>Downtime (Jam)</th>
            <th>Target Qty</th>
            <th>Actual Qty</th>
            <th>Reject Qty</th>
            <th>Availability (%)</th>
            <th>Performance (%)</th>
            <th>Quality (%)</th>
            <th>OEE (%)</th>
        </tr>
    </thead>
    <tbody>
        @foreach($rows as $row)
            <tr>
                <td>{{ \Carbon\Carbon::parse($row['date'])->format('d/m/Y') }}</td>
                <td>{{ $row['work_hours'] }}</td>
                <td>{{ $row['downtime_hours'] }}</td>
                <td>{{ $row['target_qty'] }}</td>
                <td>{{ $row['actual_qty'] }}</td>
                <td>{{ $row['reject_qty'] }}</td>
                <td>{{ $row['availability'] }}</td>
                <td>{{ $row['performance'] }}</td>
                <td>{{ $row['quality'] }}</td>
                <td>{{ $row['oee'] }}</td>
            </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr style="font-weight: bold; background-color: #e5e7eb;">
            <td>TOTAL / RINGKASAN PERIODE</td>
            <td>{{ $summary['work_hours'] }}</td>
            <td>{{ $summary['downtime_hours'] }}</td>
            <td>{{ $summary['target_qty'] }}</td>
            <td>{{ $summary['actual_qty'] }}</td>
            <td>{{ $summary['reject_qty'] }}</td>
            <td>{{ $summary['availability'] }}</td>
            <td>{{ $summary['performance'] }}</td>
            <td>{{ $summary['quality'] }}</td>
            <td>{{ $summary['oee'] }}</td>
        </tr>
    </tfoot>
</table>
